### PR TITLE
Install instructions for Paperpile

### PR DESCRIPTION
**Pull request by agruber**

### CODE REVIEW

**Comment by adam3smith** [comment]
I'm happy with this. @rmzelle any concerns?

**Comment by rmzelle** [comment]
We should probably move the "Click the "Download Style" button above to download your style" out of each subsection and to the top, so that we don't have to repeat it over and over.

Also, @agruber, I assume "Citations Styles" is a typo? Should that be "Citation Styles"?

**Comment by rmzelle** [comment]
I added a few more changes. See https://github.com/citation-style-language/csl-editor-demo-site/pull/16, which can replace this PR.

(still wondering whether there is a typo in @agruber's text; didn't check it in Paperpile)

**Comment by agruber** [comment]
Yes, that was a typo. Thanks for catching that.

**Comment by adam3smith** [comment]
I'm hoping to redeploy the site over the weekend.

**Comment by rmzelle** [comment]
> Yes, that was a typo. Thanks for catching that.

Okay, thanks. Now fixed: https://github.com/citation-style-language/csl-editor-demo-site/commit/493dbc7ddd9df9d1d6bcd28b0f7dc8f5e7ca2f0e

**Pull request closed without merging**
